app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls')),
    path('libros/', include('libros.urls')),
    path('prestamos/', include('prestamos.urls')),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

libros/urls.py
from django.urls import path

from . import views

app_name = 'libros'
urlpatterns = [
    path("", views.index, name="index"),
    path("alta_libro", views.alta_libro, name="alta_libro"),
    path("borrar/<int:libro_id>", views.borrar, name="borrar"),
    path("ver/<int:libro_id>", views.ver, name="ver"),
    path("editar/<int:libro_id>", views.editar, name="editar"),


]

prestamos/urls.py
from django.urls import path

from . import views
app_name = 'prestamos'
urlpatterns = [
    path("", views.index, name="index"),
    path("solicitar/<int:libro_id>", views.solicitar, name="solicitar"),
    path("aceptar/<int:prestamos_id>", views.aceptar, name="aceptar"),
    path("cancelar/<int:prestamos_id>", views.cancelar, name="cancelar"),

]

usuarios/urls.py
from django.urls import path

from . import views
app_name = 'usuarios'
urlpatterns = [
    path("", views.index, name="index"),
    path("registro/", views.registro, name="registro"),
    path("login/", views.login, name="login"),
]

libros/models.py
from django.db import models
from usuarios.models import Usuario  # Importamos el modelo Usuario

class Libro(models.Model):
    libro_id = models.AutoField(primary_key=True)
    titulo = models.CharField(max_length=200)
    imagen = models.ImageField(upload_to='libros/media')
    descripcion = models.TextField()
    # Relación: cada libro pertenece a un usuario
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)

    def __str__(self):
        return self.titulo


# Create your models here.

libros/forms.py
from django import forms
from .models import Libro

class LibroForm(forms.ModelForm):
    class Meta:
        model = Libro
        fields = ['titulo', 'descripcion', 'imagen']
        
        

libros/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Libro
from .forms import LibroForm
from prestamos.models import Prestamo, Estado


def index(request):
    if(request.session.get('usuario_id')): 
        libros = Libro.objects.filter(usuario_id=request.session.get('usuario_id'))
        return render(request, 'index.html', {'libros': libros}) 
    else:
        #redirijo a la pagina de login
        return redirect('usuarios:login')

def alta_libro(request):
    if request.method == 'POST':
        form = LibroForm(request.POST, request.FILES)
        if form.is_valid():
            form.instance.usuario_id = request.session.get('usuario_id')
            form.save()
            return redirect('libros:index')  # Redirige a la lista de libros, por ejemplo.
    else:
        form = LibroForm()
    return render(request, 'alta_libro.html', {'form': form})

def borrar(request, libro_id):
    libro = Libro.objects.get(libro_id=libro_id)
    libro.delete()
    return redirect('libros:index')
  
def ver(request, libro_id):
    libro = Libro.objects.get(libro_id=libro_id)
    prestamos = libro.prestamos.all()
    return render(request, 'ver.html', {'libro': libro, 'prestamos': prestamos})

def editar(request,libro_id):
    libro = Libro.objects.get(libro_id=libro_id)
    if request.method == 'POST':
        form = LibroForm(request.POST, request.FILES, instance=libro)
        if form.is_valid():
            form.save()
            return redirect('libros:index')  # Redirige a la lista de libros, por ejemplo.
    else:
        form = LibroForm(instance=libro)
    return render(request, 'alta_libro.html', {'form': form})

libros/templates/alta_libro.html
{% extends 'base.html' %}

{% block content %}
<h3>Alta de libro</h3>
<hr>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar Libro</button>
</form>
{% endblock %}

libros/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>

<body>
    <nav>
        <!-- Mostrar nombre de usuario logeado y cerrar sesion-->        
        <p>Hola, {{ request.session.nombre }}</p>
        <a href="{% url 'usuarios:login' %}">Cerrar sesion</a>
        <a href="{% url 'usuarios:login' %}">Inicio</a>
        <a href="{% url 'libros:index' %}">Libros</a>
        <a href="{% url 'prestamos:index' %}">Prestamos</a>
    </nav>
    {% block content %}

    {% endblock %}
    <footer>
        <p>Este es el pie de pagina</p>
    </footer>
</body>

</html>

libros/templates/index.html
<!--cargar plantilla base.html-->
{% extends 'base.html' %}

{% block content %}
    <h3>Listados de libros</h3>
    <hr>
    <table>
        <thead>
            <tr>
                <th>Titulo</th>
                <th>Descripción</th>
                <th>Imagen</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for libro in libros %}
                <tr>
                    <td>{{ libro.titulo }}</td>
                    <td>{{ libro.descripcion }}</td>
                    <td><img src="{{ libro.imagen.url }}" alt="" width="100"></td>
                    <td>
                    <!--Mostrar solo borrar sino tiene prestamos-->
                    {% if libro.prestamos.count == 0 %}
                        <a href="{% url 'libros:borrar' libro.libro_id%}"><i class="fa-solid fa-trash"></i></a>
                    {% endif %}                      
                       <a href="{% url 'libros:ver' libro.libro_id%}"><i class="fa-solid fa-eye"></i></a>
                       <a href="{% url 'libros:editar' libro.libro_id%}"><i class="fa-solid fa-pen-to-square"></i></a>
                    </td>
                </tr>
            {% endfor %}
    </table>
    <hr>
    <a href="{% url 'libros:alta_libro' %}">Crear libro</a>
{% endblock %}

libros/templates/ver.html
{% extends 'base.html' %}
{% block content %}
    <h3>Detalle del libro</h3>
    <hr>
    <h4>{{ libro.titulo }}</h4>
    <p>{{ libro.descripcion }}</p>
    <img src="{{ libro.imagen.url }}" alt="" width="200">
    <hr>
    <!--mostrar los prestamos-->
    <h4>Prestamos</h4>
    <ul>
        {% for prestamo in prestamos %}
            <li>
                <p>
                    {{prestamo.prestamos_id}} - {{ prestamo.fecha_solicitud }} - {{ prestamo.fecha_devolucion }} - {{prestamo.usuario.nombre}} {{prestamo.estado.descripcion}}
                </p>
                <p>
                    <a href="{% url 'prestamos:aceptar' prestamo.prestamos_id%}">Aceptar</a> 
                    <a href="{% url 'prestamos:cancelar' prestamo.prestamos_id%}">Cancelar</a> 
                </p>
            </li>
        
            {% endfor %}
    <hr>
    <a href="{% url 'libros:index' %}">Volver</a>
{% endblock %}