app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls')),
    path('libros/', include('libros.urls')),
    path('prestamos/', include('prestamos.urls')),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

prestamos/urls.py
from django.urls import path

from . import views
app_name = 'prestamos'
urlpatterns = [
    path("", views.index, name="index"),
    path("solicitar/<int:libro_id>", views.solicitar, name="solicitar"),
    path("aceptar/<int:prestamos_id>", views.aceptar, name="aceptar"),
    path("cancelar/<int:prestamos_id>", views.cancelar, name="cancelar"),

]

prestamos/models.py
from django.db import models
from usuarios.models import Usuario
from libros.models import Libro

class Estado(models.Model):
    estado_id = models.AutoField(primary_key=True)
    descripcion = models.CharField(max_length=50)

    def __str__(self):
        return self.descripcion

class Prestamo(models.Model):
    prestamos_id = models.AutoField(primary_key=True)
    libro = models.ForeignKey(Libro, on_delete=models.CASCADE,related_name='prestamos') # Libro que se presta
    # Usuario que solicita el préstamo
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    fecha_solicitud = models.DateField(auto_now_add=True)
    fecha_devolucion = models.DateField(null=True, blank=True)
    estado = models.ForeignKey(Estado, on_delete=models.CASCADE)

    def __str__(self):
        return f"Préstamo {self.prestamos_id} - {self.libro.titulo}"

prestamos/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Libro,Prestamo

def index(request):
    if(request.session.get('usuario_id')): 
        #obtengo los libros que no son del usuario logeado y excluir los libros prestados (estado=3)
        libros_disponibles = Libro.objects.exclude(usuario_id=request.session.get('usuario_id')).exclude(libro_id__in=Prestamo.objects.filter(estado_id=3).values('libro_id'))           
        #obtengo los libros que he solicitado
        solicitudes_prestamos = Prestamo.objects.filter(usuario_id=request.session.get('usuario_id'))
        return render(request, 'prestamos/index.html', {'libros': libros_disponibles, 'solicitudes_prestamos': solicitudes_prestamos}) 
    else:
        #redirijo a la pagina de login
        return redirect('usuarios:login')
 
def solicitar(request, libro_id):
    libro = Libro.objects.get(libro_id=libro_id)
    #no solicitar libro ya solicitado
    if(Prestamo.objects.filter(libro_id=libro_id,estado_id=1)):
        return redirect('prestamos:index')
    prestamo = Prestamo(libro=libro, usuario_id=request.session.get('usuario_id'), estado_id=1)
    prestamo.save()
    return redirect('prestamos:index')  # Redirige a la lista de libros, por ejemplo.   

def aceptar(request, prestamos_id):
    prestamo = Prestamo.objects.get(prestamos_id=prestamos_id,estado_id=1)
    prestamo.estado_id = 3
    prestamo.save()
    return redirect('prestamos:index')  # Redirige a la lista de libros, por ejemplo.

def cancelar(request, prestamos_id):
    prestamo = Prestamo.objects.get(prestamos_id=prestamos_id,estado_id=1)
    prestamo.estado_id = 2
    prestamo.save()
    return redirect('prestamos:index')  # Redirige a la lista de libros, por ejemplo.

prestamos/templates/prestamos/index.html
<!--cargar plantilla base.html-->
{% extends 'base.html' %}

{% block content %}
 <h1>Libros de prestamo</h1>
    <hr>
    <!--mostrar libros-->
    {% for libro in libros %}
        <div>
            <h2>{{ libro.titulo }}</h2>
            <p>{{ libro.descripcion }}</p>
            <img src="{{ libro.imagen.url }}" alt="" width="100">
            <a href="{% url 'prestamos:solicitar' libro.libro_id%}"><i class="fa-solid fa-basket-shopping"></i></a>
        </div>
    {% endfor %}
    <hr>
    <h2>Solicitudes realizadas</h2>
    <table>
        <thead>
            <th>titulo</th>
            <th>fecha solicitud</th>
            <th>fecha devolucion</th>
            <th>estado</th>            
        </thead>
        <tbody>
            {% for prestamo in solicitudes_prestamos %}
                <tr>
                    <td>{{ prestamo.libro.titulo }}</td>
                    <td>{{ prestamo.fecha_solicitud }}</td>
                    <td>{{ prestamo.fecha_devolucion }}</td>
                    <td>{{ prestamo.estado.descripcion }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}